name: "Render Quarto"
author: "Paul Villanueva"
description: "Renders a repository of documents with Quarto"
runs:
  using: "composite"
  steps: 
    - name: "Install Quarto and render"
      uses: quarto-dev/quarto-actions/install-quarto@v1
    - run: |
        if [ ! -z "${{ inputs.project_directory }}" ]
        then
          echo "Rendering from ${{ inputs.project_directory }}"
          cd "${{ inputs.project_directory }}"
        fi

        if [[ "${{ inputs.output_format }}" == "pdf" ]]
        then 
          quarto tools install tinytex
        fi

        if [ -z "${{ inputs.output_format }}" ]
        then
          quarto render 
        else
          quarto render --to "${{ inputs.output_format }}"
        fi

      shell: bash

inputs:
  output_format:
    description: 'The format Quarto will render'
    required: false
    default: ""
  project_directory:
    description: 'The directory to render from'
    required: false
    default: ""