name: "Render Quarto"
author: "Paul Villanueva"
description: "Renders a repository of documents with Quarto"
runs:
  using: "composite"
  steps: 
    - name: "Install Quarto"
      uses: quarto-dev/quarto-actions/install-quarto@v1
    - run: | 
        quarto render
      shell: bash
